
  - name: Create Database
    rds:
      region: sa-east-1
      command: create
      instance_name: new-database
      db_engine: MySQL
      size: 10
      instance_type: db.m1.small
      username: redmine_mysql
      password: redmine!123456
      subnet: "{{ subnet['subnet']['id'] }}"