---
  - name: Provisioning Instance with Redmine AMI
    hosts: local
    connection: local
    gather_facts: false
    tasks:
      - include: provisioning.yaml
      - include: database.yaml
      - include: cdn.yaml